@startuml
!include .\\MilitaryRecruitment.Api\Program.puml
!include .\\MilitaryRecruitment.DataAccess\MilitaryRecruitmentDbContext.puml
!include .\\MilitaryRecruitment.DataAccess\UnitOfWork.puml
!include .\\MilitaryRecruitment.Api\Controllers\ApplicationsController.puml
!include .\\MilitaryRecruitment.Api\Controllers\CandidatesController.puml
!include .\\MilitaryRecruitment.Api\Controllers\VacanciesController.puml
!include .\\MilitaryRecruitment.BusinessLogic\Interfaces\IApplicationService.puml
!include .\\MilitaryRecruitment.BusinessLogic\Interfaces\ICandidateService.puml
!include .\\MilitaryRecruitment.BusinessLogic\Interfaces\IVacancyService.puml
!include .\\MilitaryRecruitment.BusinessLogic\Services\ApplicationService.puml
!include .\\MilitaryRecruitment.BusinessLogic\Services\CandidateService.puml
!include .\\MilitaryRecruitment.BusinessLogic\Services\VacancyService.puml
!include .\\MilitaryRecruitment.DataAccess\Entities\Application.puml
!include .\\MilitaryRecruitment.DataAccess\Entities\Candidate.puml
!include .\\MilitaryRecruitment.DataAccess\Entities\Vacancy.puml
!include .\\MilitaryRecruitment.DataAccess\Identity\AppUser.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250512202734_InitialMigrationWithIdentity.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250512202734_InitialMigrationWithIdentity.Designer.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250602204453_AddPriorityAndWasFullyChecked.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250602204453_AddPriorityAndWasFullyChecked.Designer.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250603214605_FixIsChosenByAlgorithmSpelling.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250603214605_FixIsChosenByAlgorithmSpelling.Designer.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250603215246_FixIsChosenByAlgorithmSpellingAgain.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250603215246_FixIsChosenByAlgorithmSpellingAgain.Designer.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250603215443_RenameAlgorithmColumns.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250603215443_RenameAlgorithmColumns.Designer.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250607184104_AddColumns.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250607184104_AddColumns.Designer.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250607185852_AddIdentity.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\20250607185852_AddIdentity.Designer.puml
!include .\\MilitaryRecruitment.DataAccess\Migrations\MilitaryRecruitmentDbContextModelSnapshot.puml
!include .\\MilitaryRecruitment.DataAccess\Repositories\ApplicationRepository.puml
!include .\\MilitaryRecruitment.DataAccess\Repositories\CandidateRepository.puml
!include .\\MilitaryRecruitment.DataAccess\Repositories\VacancyRepository.puml
!include .\\MilitaryRecruitment.BusinessLogic\DTOs\Application\AlgorithmResultDto.puml
!include .\\MilitaryRecruitment.BusinessLogic\DTOs\Application\ApplicationCreateDto.puml
!include .\\MilitaryRecruitment.BusinessLogic\DTOs\Application\ApplicationGetDto.puml
!include .\\MilitaryRecruitment.BusinessLogic\DTOs\Candidate\CandidateCreateDto.puml
!include .\\MilitaryRecruitment.BusinessLogic\DTOs\Candidate\CandidateGetDto.puml
!include .\\MilitaryRecruitment.BusinessLogic\DTOs\Vacancy\VacancyCreateDto.puml
!include .\\MilitaryRecruitment.BusinessLogic\DTOs\Vacancy\VacancyGetDto.puml
!include .\\MilitaryRecruitment.Api\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MilitaryRecruitment.Api\obj\Debug\net8.0\MilitaryRecruitment.Api.AssemblyInfo.puml
!include .\\MilitaryRecruitment.Api\obj\Debug\net8.0\MilitaryRecruitment.Api.GlobalUsings.g.puml
!include .\\MilitaryRecruitment.Api\obj\Debug\net8.0\MilitaryRecruitment.Api.MvcApplicationPartsAssemblyInfo.puml
!include .\\MilitaryRecruitment.Api\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MilitaryRecruitment.Api\obj\Release\net8.0\MilitaryRecruitment.Api.AssemblyInfo.puml
!include .\\MilitaryRecruitment.Api\obj\Release\net8.0\MilitaryRecruitment.Api.GlobalUsings.g.puml
!include .\\MilitaryRecruitment.BusinessLogic\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MilitaryRecruitment.BusinessLogic\obj\Debug\net8.0\MilitaryRecruitment.BusinessLogic.AssemblyInfo.puml
!include .\\MilitaryRecruitment.BusinessLogic\obj\Debug\net8.0\MilitaryRecruitment.BusinessLogic.GlobalUsings.g.puml
!include .\\MilitaryRecruitment.BusinessLogic\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MilitaryRecruitment.BusinessLogic\obj\Release\net8.0\MilitaryRecruitment.BusinessLogic.AssemblyInfo.puml
!include .\\MilitaryRecruitment.BusinessLogic\obj\Release\net8.0\MilitaryRecruitment.BusinessLogic.GlobalUsings.g.puml
!include .\\MilitaryRecruitment.DataAccess\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MilitaryRecruitment.DataAccess\obj\Debug\net8.0\MilitaryRecruitment.DataAccess.AssemblyInfo.puml
!include .\\MilitaryRecruitment.DataAccess\obj\Debug\net8.0\MilitaryRecruitment.DataAccess.GlobalUsings.g.puml
!include .\\MilitaryRecruitment.DataAccess\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MilitaryRecruitment.DataAccess\obj\Release\net8.0\MilitaryRecruitment.DataAccess.AssemblyInfo.puml
!include .\\MilitaryRecruitment.DataAccess\obj\Release\net8.0\MilitaryRecruitment.DataAccess.GlobalUsings.g.puml
@enduml
